language: php

cache:
  directories:
    - $HOME/.composer/cache/files

# https://travis-ci.community/t/xdebug-3-is-installed-by-default-breaking-builds/10748/6
env:
  global:
    - XDEBUG_MODE=coverage

matrix:
  include:
    - php: 7.1
      env:
        - 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
    - php: 7.2
    - php: 7.3
      env:
        - 'COVERAGE=yes'
    - php: 7.4
  fast_finish: true

before_install:
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || true; fi;

install:
  - export COMPOSER_FLAGS="--prefer-dist --no-interaction"
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpcs -p
  - if [[ $COVERAGE = yes ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi

after_script:
  - if [[ $COVERAGE = yes ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

notifications:
  email: false
