name: CI

on:
  push:
    branches:
      - 74.x

env:
  FORCE_COLOR: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer self-update
          composer install

      - name: Tests & Style
        run: |
          composer test-coverage
          composer phpcs

      - name: Upload Coverage
        if: github.repository_owner == 'gskema'
        run: composer upload-coverage
